services:
  react-app:
    build: .
    container_name: react-app
    ports:
      - '5173:5173'
    volumes:
      - ./src:/app/src
    command: yarn dev --host 0.0.0.0
    environment:
      - CHOKIDAR_USEPOLLING=true
